import { createRoot } from "react-dom/client";

const iframeHtml = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>embedded page</title>
    <style>
      body { margin: 0; font-family: system-ui, sans-serif; padding: 16px; }
      h1 { font-size: 18px; }
    </style>
  </head>
  <body>
    <h1>Hello from a string</h1>
    <p>This whole page came from a single HTML string.</p>
    <button id="btn">click me</button>
    <script>
      document.getElementById("btn").addEventListener("click", function () {
        document.body.style.background = "#eef6ff";
      });
    </script>
  </body>
</html>`;

const iframeHtmlMonaco = [
  "<!DOCTYPE html>",
  "<html lang=\"en\">",
  "<head>",
  "  <meta charset=\"UTF-8\" />",
  "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />",
  "  <title>Embedded Monaco Editor</title>",
  "  <style>",
  "    * { margin: 0; padding: 0; box-sizing: border-box; }",
  "    html, body { height: 100%; }",
  "    body {",
  "      display: flex;",
  "      flex-direction: column;",
  "      font-family: system-ui, sans-serif;",
  "      background: #1e1e1e;",
  "    }",
  "    header {",
  "      height: 50px;",
  "      display: flex;",
  "      gap: 8px;",
  "      align-items: center;",
  "      padding: 8px;",
  "      background: #2d2d2d;",
  "      /* margin-top: 5px; */",
  "      color: #ddd;",
  "    }",
  "    header select, header button {",
  "      padding: 6px 10px;",
  "      border: 1px solid #555;",
  "      border-radius: 4px;",
  "      background: #3c3c3c;",
  "      color: #ddd;",
  "      cursor: pointer;",
  "    }",
  "    header button:hover { background: #505050; }",
  "    #editor { flex: 1; min-height: 0; }",
  "    #output {",
  "      height: 120px;",
  "      overflow: auto;",
  "      padding: 8px;",
  "      background: #111;",
  "      color: #9ece6a;",
  "      font-family: monospace;",
  "      font-size: 13px;",
  "      white-space: pre-wrap;",
  "      border-top: 1px solid #333;",
  "    }",
  "  </style>",
  "</head>",
  "<body>",
  "  <header>",
  "    <label for=\"lang\">Language:</label>",
  "    <select id=\"lang\">",
  "      <option value=\"abap\">abap</option>",
  "      <option value=\"aes\">aes</option>",
  "      <option value=\"apex\">Apex</option>",
  "      <option value=\"azcli\">Azure CLI</option>",
  "      <option value=\"bat\">Batch</option>",
  "      <option value=\"bicep\">Bicep</option>",
  "      <option value=\"c\">C</option>",
  "      <option value=\"cameligo\">Cameligo</option>",
  "      <option value=\"clojure\">clojure</option>",
  "      <option value=\"coffeescript\">CoffeeScript</option>",
  "      <option value=\"cpp\">C++</option>",
  "      <option value=\"csharp\">C#</option>",
  "      <option value=\"csp\">CSP</option>",
  "      <option value=\"css\">CSS</option>",
  "      <option value=\"cypher\">Cypher</option>",
  "      <option value=\"dart\">Dart</option>",
  "      <option value=\"dockerfile\">Dockerfile</option>",
  "      <option value=\"ecl\">ECL</option>",
  "      <option value=\"elixir\">Elixir</option>",
  "      <option value=\"flow9\">Flow9</option>",
  "      <option value=\"freemarker2\">FreeMarker2</option>",
  "      <option value=\"fsharp\">F#</option>",
  "      <option value=\"go\">Go</option>",
  "      <option value=\"graphql\">GraphQL</option>",
  "      <option value=\"handlebars\">Handlebars</option>",
  "      <option value=\"hcl\">Terraform</option>",
  "      <option value=\"html\">HTML</option>",
  "      <option value=\"ini\">Ini</option>",
  "      <option value=\"java\">Java</option>",
  "      <option value=\"javascript\" selected>JavaScript</option>",
  "      <option value=\"json\">JSON</option>",
  "      <option value=\"julia\">julia</option>",
  "      <option value=\"kotlin\">Kotlin</option>",
  "      <option value=\"less\">Less</option>",
  "      <option value=\"lexon\">Lexon</option>",
  "      <option value=\"liquid\">Liquid</option>",
  "      <option value=\"lua\">Lua</option>",
  "      <option value=\"m3\">Modula-3</option>",
  "      <option value=\"markdown\">Markdown</option>",
  "      <option value=\"mdx\">MDX</option>",
  "      <option value=\"mips\">MIPS</option>",
  "      <option value=\"msdax\">DAX</option>",
  "      <option value=\"mysql\">MySQL</option>",
  "      <option value=\"objective-c\">Objective-C</option>",
  "      <option value=\"pascal\">Pascal</option>",
  "      <option value=\"pascaligo\">Pascaligo</option>",
  "      <option value=\"perl\">Perl</option>",
  "      <option value=\"pgsql\">PostgreSQL</option>",
  "      <option value=\"php\">PHP</option>",
  "      <option value=\"pla\">ATS (pla)</option>",
  "      <option value=\"plaintext\">Plain Text</option>",
  "      <option value=\"postiats\">ATS (postiats)</option>",
  "      <option value=\"powerquery\">Power Query</option>",
  "      <option value=\"powershell\">PowerShell</option>",
  "      <option value=\"proto\">protobuf</option>",
  "      <option value=\"pug\">Pug</option>",
  "      <option value=\"python\">Python</option>",
  "      <option value=\"qsharp\">Q#</option>",
  "      <option value=\"r\">R</option>",
  "      <option value=\"razor\">Razor</option>",
  "      <option value=\"redis\">redis</option>",
  "      <option value=\"redshift\">Redshift</option>",
  "      <option value=\"restructuredtext\">reStructuredText</option>",
  "      <option value=\"ruby\">Ruby</option>",
  "      <option value=\"rust\">Rust</option>",
  "      <option value=\"sb\">Small Basic</option>",
  "      <option value=\"scala\">Scala</option>",
  "      <option value=\"scheme\">scheme</option>",
  "      <option value=\"scss\">Sass</option>",
  "      <option value=\"shell\">Shell</option>",
  "      <option value=\"sol\">Solidity</option>",
  "      <option value=\"sparql\">sparql</option>",
  "      <option value=\"sql\">SQL</option>",
  "      <option value=\"st\">StructuredText</option>",
  "      <option value=\"swift\">Swift</option>",
  "      <option value=\"systemverilog\">SystemVerilog</option>",
  "      <option value=\"tcl\">Tcl</option>",
  "      <option value=\"twig\">Twig</option>",
  "      <option value=\"typescript\">TypeScript</option>",
  "      <option value=\"typespec\">TypeSpec</option>",
  "      <option value=\"vb\">Visual Basic</option>",
  "      <option value=\"verilog\">Verilog</option>",
  "      <option value=\"wgsl\">WGSL</option>",
  "      <option value=\"xml\">XML</option>",
  "      <option value=\"yaml\">YAML</option>",
  "    </select>",
  "    <button id=\"saveBtn\">Save</button>",
  "    <!-- <button id=\"formatBtn\">Format</button> -->",
  "    <!-- <button id=\"getValueBtn\">Get Value</button> -->",
  "    <span id=\"status\" style=\"margin-left:auto; font-size:12px; color:#888;\">Good</span>",
  "  </header>",
  "",
  "  <div id=\"editor\"></div>",
  "  <!-- <div id=\"output\">Output will appear here…</div> -->",
  "",
  "  <script src=\"https://cdn.jsdelivr.net/npm/monaco-editor@0.52.2/min/vs/loader.js\"></script>",
  "  <script>",
  "    const samples = {",
  "      javascript: `function greet(name) {\\n  return \\`Hello, \\${name}!\\`;\\n}\\n\\nconsole.log(greet(\"Monaco\"));\\n`,",
  "      typescript: `interface User {\\n  id: number;\\n  name: string;\\n}\\n\\nconst user: User = { id: 1, name: \"Ada\" };\\nconsole.log(user);\\n`,",
  "      html: `<!DOCTYPE html>\\n<html>\\n  <body>\\n    <h1>Hello, Monaco!</h1>\\n  </body>\\n</html>\\n`,",
  "      css: `body {\\n  font-family: system-ui, sans-serif;\\n  background: #1e1e1e;\\n  color: #eee;\\n}\\n`,",
  "      python: `def greet(name: str) -> str:\\n    return f\"Hello, {name}!\"\\n\\nprint(greet(\"Monaco\"))\\n`,",
  "      json: `{\\n  \"name\": \"monaco-editor\",\\n  \"version\": \"0.52.2\"\\n}\\n`,",
  "      markdown: `# Hello, Monaco!\\n\\nAn embedded **Monaco** editor in a single HTML file.\\n`",
  "    };",
  "",
  "    let editor;",
  "",
  "    const STORAGE_KEY = \"monaco-embedded:content\";",
  "",
  "    const readSavedValue = () => {",
  "      try {",
  "        return localStorage.getItem(STORAGE_KEY);",
  "      } catch {",
  "        return null;",
  "      }",
  "    };",
  "",
  "    const saveValue = (value) => {",
  "      try {",
  "        localStorage.setItem(STORAGE_KEY, value);",
  "        document.getElementById(\"status\").textContent = \"Saved\";",
  "        console.log(getHighlightedHtml(value));",
  "      } catch (err) {",
  "        document.getElementById(\"status\").textContent = \"Save failed\";",
  "        console.error(err);",
  "      }",
  "    };",
  "",
  "    const getHighlightedHtml = () =>",
  "      [...editor.getDomNode().querySelectorAll(\".view-lines > .view-line\")]",
  "        .map((line) => {",
  "          const clone = line.cloneNode(true);",
  "          clone.removeAttribute(\"style\");",
  "          clone.classList.remove(\"view-line\");",
  "          return clone.outerHTML;",
  "        }).join(\"\\n\");",
  "",
  "    require.config({",
  "      paths: { vs: \"https://cdn.jsdelivr.net/npm/monaco-editor@0.52.2/min/vs\" }",
  "    });",
  "",
  "    require([\"vs/editor/editor.main\"], function (monaco) {",
  "      const savedValue = readSavedValue();",
  "",
  "      editor = monaco.editor.create(document.getElementById(\"editor\"), {",
  "        value: savedValue ?? samples.javascript,",
  "        language: \"javascript\",",
  "        theme: \"vs-light\",",
  "        automaticLayout: false,",
  "        fontSize: 14,",
  "        minimap: { enabled: true },",
  "        scrollBeyondLastLine: false,",
  "        renderWhitespace: \"selection\",",
  "        tabSize: 2,",
  "        wordWrap: \"off\",",
  "        padding: { top: 8 }",
  "      });",
  "",
  "      monaco.editor.onDidChangeMarkers(() => {",
  "        const markers = monaco.editor.getModelMarkers({});",
  "        document.getElementById(\"status\").textContent =",
  "          markers.length ? `${markers.length} problem(s)` : \"No problems\";",
  "      });",
  "",
  "      document.getElementById(\"saveBtn\").addEventListener(\"click\", (e) => {",
  "        saveValue(editor.getValue());",
  "        const model = editor.getModel();",
  "      });",
  "",
  "      document.addEventListener(\"keydown\", (e) => {",
  "        if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === \"s\") {",
  "          e.preventDefault();",
  "          saveValue(editor.getValue());",
  "        }",
  "      });",
  "",
  "      document.getElementById(\"lang\").addEventListener(\"change\", (e) => {",
  "        const lang = e.target.value;",
  "        const model = editor.getModel();",
  "        saveValue(model.getValue());",
  "",
  "        monaco.editor.setModelLanguage(model, lang);",
  "        if (samples[lang]) {",
  "          model.setValue(samples[lang]);",
  "        }",
  "      });",
  "",
  "      document.getElementById(\"formatBtn\")?.addEventListener(\"click\", () => {",
  "        editor.getAction(\"editor.action.formatDocument\").run();",
  "      });",
  "",
  "      document.getElementById(\"getValueBtn\")?.addEventListener(\"click\", () => {",
  "        document.getElementById(\"output\").textContent = editor.getValue();",
  "      });",
  "    });",
  "  </script>",
  "</body>",
  "</html>",
  "",
].join("\n");

createRoot(document.getElementById("root")).render(
  <div style={{ height: "100vh" }}>
    <iframe
      title="monaco"
      srcDoc={iframeHtmlMonaco}
      sandbox="allow-scripts allow-same-origin"
      style={{ width: "100%", height: "100%", border: 0 }}
    />
  </div>,
);
